// <auto-generated />
using GateKeeper.Core.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GateKeeper.Core.Migrations
{
    [DbContext(typeof(AddressesDbContext))]
    partial class AddressesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("GateKeeper.Core.Models.AllowedDomains", b =>
                {
                    b.Property<string>("Domain")
                        .HasColumnType("TEXT");

                    b.HasKey("Domain");

                    b.ToTable("AllowedDomains", (string)null);
                });

            modelBuilder.Entity("GateKeeper.Core.Models.ForeingAddresses", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReceivedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("ForeingAddresses", (string)null);
                });

            modelBuilder.Entity("GateKeeper.Core.Models.LocalMonitoredAddresses", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsReplyAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.HasKey("Email");

                    b.ToTable("localMonitoredAddresses", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
